#!/bin/sh

set -eu

php_version() {
    php -r 'printf("%u.%u\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION);'
}

git_is_dirty() {
    if ! git diff-index --exit-code --ignore-submodules HEAD >/dev/null; then
        return 0
    fi

    return 1
}

modify_composerjson() {
    jq "$1" < composer.json > .composer.json.tmp
    mv .composer.json.tmp composer.json
}

main() {
    PREFERENCE="$1"; shift # highest/lowest

    WITH_PHP="${WITH_PHP:-$(php_version)}" # 5.6/7.2/etc

    COMPOSER_ARGS="--no-progress --prefer-dist"

    if git_is_dirty; then
        echo "Working tree is dirty, aborting" >&2
        return 1
    fi

    echo "Using PHP ${WITH_PHP}" >&2

    if [ "$PREFERENCE" = "lowest" ];
    then
        COMPOSER_ARGS="${COMPOSER_ARGS} --prefer-lowest --prefer-stable"
    fi

    if [ "$WITH_PHP" = "7.4" ]; then
        # PHP 7.4+ needs this fix: https://github.com/sebastianbergmann/phpunit/commit/e11397fed729bfef7a9c76f7b193c27ad5710f6b
        modify_composerjson '.conflict["phpunit/phpunit"] = "< 7.5.15 || >= 8 < 8.3.0"'
    fi

    if [ "$WITH_PHP" = "8.1" ] || [ "$WITH_PHP" = "8.2" ]; then
        # PHP 8.1 needs this fix: https://github.com/sebastianbergmann/phpunit/commit/83491f4d19d18c868829a013f0ee0839dd53c684
        modify_composerjson '.conflict["phpunit/phpunit"] = ">= 8 < 8.5.14"'
    fi

    if [ "$WITH_PHP" = "8.2" ]; then
        modify_composerjson '.conflict["webmozart/assert"] = "< 1.11.0"'
    fi

    composer update $COMPOSER_ARGS

    # Undo modifications to composer.json
    git checkout -- composer.json
}

main "$@"
