name: Main

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        deps:
          - highest
          - lowest
        include:
          - os: ubuntu-latest
            php: '8.5'
            phpstan: 1
          - os: ubuntu-latest
            php: '8.1'
            phpstan: 1
          - os: ubuntu-latest
            php: '8.5'
            coverage: 1
          - os: ubuntu-latest
            php: '8.1'
            coverage: 1
      fail-fast: true
    name: PHP ${{ matrix.php }} / ${{ matrix.deps }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.php == '5.6' && 'composer:2.2' || 'composer' }}
      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Enable assertions
        run: echo 'zend.assertions=1' | sudo tee /etc/php/${{ matrix.php }}/cli/conf.d/assert.ini >/dev/null
      - name: Install dependencies
        run: |
          sudo phpdismod xdebug

          export WITH_PHP="${{ matrix.php }}"
          export WITH_PHPSTAN="${{ matrix.phpstan }}"

          scripts/deps "${{ matrix.deps }}"
      - name: PHPUnit
        run: |
          vendor/bin/phpunit --version | head -n1 >&2

          if [ "${{ matrix.coverage }}" = "1" ]; then
            sudo phpenmod xdebug
            vendor/bin/phpunit $args --coverage-clover=coverage.xml
            sudo phpdismod xdebug
          else
            vendor/bin/phpunit $args
          fi
      - name: PHPStan
        if: matrix.phpstan == 1
        run: |
          composer bin cs2pr install
          composer bin phpstan install

          (vendor/bin/phpstan analyse -c .phpstan.neon --no-progress --error-format=checkstyle || true) | vendor/bin/cs2pr
      - name: Upload coverage reports to Codecov
        if: matrix.coverage == 1
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

  backwards-compatibility-check:
    name: Backwards Compatibility Check
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.5"
      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer update
          composer bin bc-check install
      - name: Check for BC breaks
        run: "vendor/bin/roave-backward-compatibility-check"
